"""Add sections

Revision ID: 030c713bf38c
Revises: 06665fd8a076
Create Date: 2020-06-13 17:59:49.672941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030c713bf38c'
down_revision = '06665fd8a076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
