"""Update books model

Revision ID: 28ce7bb116c9
Revises: 4679bd90491c
Create Date: 2020-06-13 20:59:32.054518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ce7bb116c9'
down_revision = '4679bd90491c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'books', ['title'])
    op.create_unique_constraint(None, 'genres', ['name'])
    op.create_unique_constraint(None, 'sections', ['name'])
    op.create_unique_constraint(None, 'tags', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'sections', type_='unique')
    op.drop_constraint(None, 'genres', type_='unique')
    op.drop_constraint(None, 'books', type_='unique')
    # ### end Alembic commands ###
