"""Add seasons, episodes

Revision ID: 2d9ed7638712
Revises: c7019140e0f7
Create Date: 2020-06-18 22:10:16.980648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d9ed7638712'
down_revision = 'c7019140e0f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
