"""Update users model

Revision ID: 3a5dcd078b7a
Revises: 1d740fe2e672
Create Date: 2020-07-15 10:03:21.428096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5dcd078b7a'
down_revision = '1d740fe2e672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'books_authors', 'books', ['book_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'books_authors', 'authors', ['author_id'], ['id'])
    op.create_foreign_key(None, 'books_genres', 'genres', ['genre_id'], ['id'])
    op.create_foreign_key(None, 'books_genres', 'books', ['book_id'], ['id'])
    op.create_foreign_key(None, 'books_painters', 'painters', ['painter_id'], ['id'])
    op.create_foreign_key(None, 'books_painters', 'books', ['book_id'], ['id'])
    op.create_foreign_key(None, 'books_publishers', 'books', ['book_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'books_publishers', 'publishers', ['publisher_id'], ['id'])
    op.create_foreign_key(None, 'books_release_formates', 'books', ['book_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'books_sections', 'sections', ['section_id'], ['id'])
    op.create_foreign_key(None, 'books_sections', 'books', ['book_id'], ['id'])
    op.create_foreign_key(None, 'books_tags', 'books', ['book_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'books_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'books_translators', 'books', ['book_id'], ['id'])
    op.create_foreign_key(None, 'books_translators', 'translators', ['translator_id'], ['id'])
    op.add_column('users', sa.Column('nickname', sa.Unicode(), nullable=True))
    op.create_unique_constraint(None, 'users', ['nickname'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'nickname')
    op.drop_constraint(None, 'books_translators', type_='foreignkey')
    op.drop_constraint(None, 'books_translators', type_='foreignkey')
    op.drop_constraint(None, 'books_tags', type_='foreignkey')
    op.drop_constraint(None, 'books_tags', type_='foreignkey')
    op.drop_constraint(None, 'books_sections', type_='foreignkey')
    op.drop_constraint(None, 'books_sections', type_='foreignkey')
    op.drop_constraint(None, 'books_release_formates', type_='foreignkey')
    op.drop_constraint(None, 'books_publishers', type_='foreignkey')
    op.drop_constraint(None, 'books_publishers', type_='foreignkey')
    op.drop_constraint(None, 'books_painters', type_='foreignkey')
    op.drop_constraint(None, 'books_painters', type_='foreignkey')
    op.drop_constraint(None, 'books_genres', type_='foreignkey')
    op.drop_constraint(None, 'books_genres', type_='foreignkey')
    op.drop_constraint(None, 'books_authors', type_='foreignkey')
    op.drop_constraint(None, 'books_authors', type_='foreignkey')
    # ### end Alembic commands ###
