"""Update book model

Revision ID: 3e579fa9c3ff
Revises: 9310b895e5c8
Create Date: 2020-06-19 23:51:11.565901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e579fa9c3ff'
down_revision = '9310b895e5c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
