"""Add seasons, episodes

Revision ID: 4222e759b4c7
Revises: fd3eac2b2030
Create Date: 2020-06-18 22:35:38.810663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4222e759b4c7'
down_revision = 'fd3eac2b2030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('seasons_name_key', 'seasons', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('seasons_name_key', 'seasons', ['name'])
    # ### end Alembic commands ###
