"""Update books model

Revision ID: 4679bd90491c
Revises: 030c713bf38c
Create Date: 2020-06-13 20:54:04.779849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4679bd90491c'
down_revision = '030c713bf38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('cover', sa.Unicode(), nullable=True))
    op.drop_column('books', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('books', 'cover')
    # ### end Alembic commands ###
