"""Add enum props to book model

Revision ID: 6fe6e08145c9
Revises: 3e579fa9c3ff
Create Date: 2020-06-20 23:15:59.122503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '6fe6e08145c9'
down_revision = '3e579fa9c3ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    agelimit = postgresql.ENUM(
        'unlimited',
        'sixteen',
        'eighteen',
        name='agelimit')
    agelimit.create(op.get_bind())

    releaseformat = postgresql.ENUM(
        'color',
        'web',
        'sigle',
        'compilation',
        'doujinshi',
        name='releaseformat')
    releaseformat.create(op.get_bind())

    translationstatus = postgresql.ENUM(
        'complete',
        'processing',
        'frozen',
        'no_translator',
        name='translationstatus')
    translationstatus.create(op.get_bind())

    op.add_column('books', sa.Column('age_limit', sa.Enum(
        'unlimited', 'sixteen', 'eighteen', name='agelimit'), nullable=False))
    op.add_column('books', sa.Column(
        'background_image', sa.Unicode(), nullable=True))
    op.add_column('books', sa.Column(
        'cover_image', sa.Unicode(), nullable=True))
    op.add_column('books', sa.Column('release_format', sa.Enum(
        'color', 'web', 'sigle', 'compilation', 'doujinshi', name='releaseformat'), nullable=False))
    op.add_column('books', sa.Column('translation_status', sa.Enum(
        'complete', 'processing', 'frozen', 'no_translator', name='translationstatus'), nullable=False))
    op.drop_column('books', 'cover')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('cover', sa.VARCHAR(),
                                     autoincrement=False, nullable=True))
    op.drop_column('books', 'translation_status')
    op.drop_column('books', 'release_format')
    op.drop_column('books', 'cover_image')
    op.drop_column('books', 'background_image')
    op.drop_column('books', 'age_limit')
    # ### end Alembic commands ###
