"""Update seasons/episodes

Revision ID: 977f11371301
Revises: ea54ba40d095
Create Date: 2020-10-01 21:01:15.642218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977f11371301'
down_revision = 'ea54ba40d095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('number', sa.Unicode(), nullable=True))
    op.add_column('seasons', sa.Column('number', sa.Unicode(), nullable=True))
    op.drop_column('seasons', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seasons', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('seasons', 'number')
    op.drop_column('episodes', 'number')
    # ### end Alembic commands ###
