"""Update books model delete

Revision ID: c7019140e0f7
Revises: c72674662f8b
Create Date: 2020-06-17 20:21:17.259098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7019140e0f7'
down_revision = 'c72674662f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
