"""Update books model delete

Revision ID: c72674662f8b
Revises: f571203d18df
Create Date: 2020-06-17 00:33:19.506356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c72674662f8b'
down_revision = 'f571203d18df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_title_key', 'books', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('books_title_key', 'books', ['title'])
    # ### end Alembic commands ###
