"""Update books model delete

Revision ID: f571203d18df
Revises: 28ce7bb116c9
Create Date: 2020-06-16 22:52:19.799133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f571203d18df'
down_revision = '28ce7bb116c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'books_genres', 'books', ['book_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books_genres', type_='foreignkey')
    # ### end Alembic commands ###
